import Navbar from '@/components/navbar';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs/app-beta';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
